export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

export const UPDATE_MESSAGE = "ADD_NEW_MESSAGE";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const UPDATE_CHART_DATA = "UPDATE_CHART_DATA";